name: clang-tidy

on:
  schedule:
    - cron: "0 */4 * * *" # every 4 hours
  workflow_dispatch: {}

env:
  BUILD_TYPE: RelWithDebInfo
  BUILD_DIR: build
  CLANG_TIDY_CHECKS: "-*,bugprone-use-after-move"

permissions: {}

jobs:
  read-toolchain:
    uses: ./.github/workflows/read-toolchain.yaml
  benchmark-gha:
    name: Run clang-tidy GHA
    needs:
      - read-toolchain
    runs-on: ubuntu-latest
    container: ${{ needs.read-toolchain.outputs.image }}
    steps:
      - env:
          IMAGE: ${{ needs.read-toolchain.image }}
        run: |
          echo ${{ needs.read-toolchain.image }}
      - uses: actions/checkout@v4
        with:
          repository: scylladb/scylladb
          ref: master
          submodules: true
      - run: |
          sudo dnf -y install clang-tools-extra
      - name: Generate the building system
        run: |
          cmake                                         \
            -DCMAKE_BUILD_TYPE=$BUILD_TYPE              \
            -DCMAKE_C_COMPILER=clang                    \
            -DScylla_USE_LINKER=ld.lld                  \
            -DCMAKE_CXX_COMPILER=clang++                \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON          \
            -DCMAKE_CXX_CLANG_TIDY="clang-tidy;--checks=$CLANG_TIDY_CHECKS" \
            -G Ninja                                    \
            -B $BUILD_DIR                               \
            -S .
      # see https://github.com/actions/toolkit/blob/main/docs/problem-matchers.md
      - run: |
          echo "::add-matcher::.github/clang-matcher.json"
      - name: Build with clang-tidy enabled
        run: |
          cmake --build $BUILD_DIR --target scylla
      - run: |
          echo "::remove-matcher owner=clang::"
  benchmark-depot:
    name: Run clang-tidy Depot (4 CPUs)
    needs:
      - read-toolchain
    runs-on: depot-ubuntu-latest-4
    container: ${{ needs.read-toolchain.outputs.image }}
    steps:
      - env:
          IMAGE: ${{ needs.read-toolchain.image }}
        run: |
          echo ${{ needs.read-toolchain.image }}
      - uses: actions/checkout@v4
        with:
          repository: scylladb/scylladb
          ref: master
          submodules: true
      - run: |
          sudo dnf -y install clang-tools-extra
      - name: Generate the building system
        run: |
          cmake                                         \
            -DCMAKE_BUILD_TYPE=$BUILD_TYPE              \
            -DCMAKE_C_COMPILER=clang                    \
            -DScylla_USE_LINKER=ld.lld                  \
            -DCMAKE_CXX_COMPILER=clang++                \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON          \
            -DCMAKE_CXX_CLANG_TIDY="clang-tidy;--checks=$CLANG_TIDY_CHECKS" \
            -G Ninja                                    \
            -B $BUILD_DIR                               \
            -S .
      # see https://github.com/actions/toolkit/blob/main/docs/problem-matchers.md
      - run: |
          echo "::add-matcher::.github/clang-matcher.json"
      - name: Build with clang-tidy enabled
        run: |
          cmake --build $BUILD_DIR --target scylla -j 4
      - run: |
          echo "::remove-matcher owner=clang::"
